INFO 2024-04-07 20:28:05,850 views 10344 4732 Посещение страницы "о себе"
INFO 2024-04-07 20:28:05,852 basehttp 10344 4732 "GET /about/ HTTP/1.1" 200 408
WARNING 2024-04-07 20:28:07,844 log 10344 4732 Not Found: /фищге
WARNING 2024-04-07 20:28:07,845 basehttp 10344 4732 "GET /%D1%84%D0%B8%D1%89%D0%B3%D0%B5 HTTP/1.1" 404 2459
INFO 2024-04-07 20:28:12,435 views 10344 4732 Посещение страницы "о себе"
INFO 2024-04-07 20:28:12,436 basehttp 10344 4732 "GET /about/ HTTP/1.1" 200 408
INFO 2024-04-08 18:10:58,123 autoreload 8264 14864 Watching for file changes with StatReloader
INFO 2024-04-08 18:11:04,796 views 8264 11336 Посещение страницы "главная"
INFO 2024-04-08 18:11:04,805 basehttp 8264 11336 "GET / HTTP/1.1" 200 240
INFO 2024-04-08 18:11:10,081 views 8264 11336 Посещение страницы "о себе"
INFO 2024-04-08 18:11:10,085 basehttp 8264 11336 "GET /about/ HTTP/1.1" 200 408
INFO 2024-04-09 18:39:43,939 autoreload 4428 10084 Watching for file changes with StatReloader
INFO 2024-04-11 12:52:32,764 autoreload 384 12664 Watching for file changes with StatReloader
WARNING 2024-04-11 12:52:35,925 log 384 604 Not Found: /
WARNING 2024-04-11 12:52:35,929 basehttp 384 604 "GET / HTTP/1.1" 404 2283
WARNING 2024-04-11 12:52:36,024 log 384 604 Not Found: /favicon.ico
WARNING 2024-04-11 12:52:36,024 basehttp 384 604 "GET /favicon.ico HTTP/1.1" 404 2334
INFO 2024-04-12 14:19:39,914 autoreload 14656 11172 Watching for file changes with StatReloader
WARNING 2024-04-12 14:19:43,085 log 14656 9460 Not Found: /
WARNING 2024-04-12 14:19:43,085 basehttp 14656 9460 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:19:55,637 views 14656 9460 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 14:19:55,701 log 14656 9460 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw3_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw3_app/index.html
ERROR 2024-04-12 14:19:55,701 basehttp 14656 9460 "GET /homework3/ HTTP/1.1" 500 80691
INFO 2024-04-12 14:21:10,008 autoreload 14656 11172 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 14:21:10,850 autoreload 14776 12948 Watching for file changes with StatReloader
WARNING 2024-04-12 14:21:12,402 log 14776 3328 Not Found: /
WARNING 2024-04-12 14:21:12,403 basehttp 14776 3328 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:21:20,740 views 14776 3328 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 14:21:20,815 log 14776 3328 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw_app3/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-12 14:21:20,822 basehttp 14776 3328 "GET /homework3/ HTTP/1.1" 500 125463
INFO 2024-04-12 14:24:16,110 views 14776 3328 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:24:16,116 basehttp 14776 3328 "GET /homework3/ HTTP/1.1" 200 433
WARNING 2024-04-12 14:24:44,795 log 14776 3328 Not Found: /homework3/client_orders_view/
WARNING 2024-04-12 14:24:44,796 basehttp 14776 3328 "GET /homework3/client_orders_view/ HTTP/1.1" 404 2956
WARNING 2024-04-12 14:25:24,724 log 14776 3328 Not Found: /homework3/ client/1/orders/
WARNING 2024-04-12 14:25:24,724 basehttp 14776 3328 "GET /homework3/%20client/1/orders/ HTTP/1.1" 404 2952
ERROR 2024-04-12 14:25:40,902 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:25:40,917 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
ERROR 2024-04-12 14:26:58,996 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:26:58,996 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75143
ERROR 2024-04-12 14:27:01,595 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:27:01,595 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75143
WARNING 2024-04-12 14:27:49,060 log 14776 3328 Not Found: /homework3/client
WARNING 2024-04-12 14:27:49,061 basehttp 14776 3328 "GET /homework3/client HTTP/1.1" 404 2917
ERROR 2024-04-12 14:28:12,775 log 14776 3328 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:28:12,775 basehttp 14776 3328 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
INFO 2024-04-12 14:37:49,881 autoreload 7344 13644 Watching for file changes with StatReloader
WARNING 2024-04-12 14:37:57,934 log 7344 12584 Not Found: /
WARNING 2024-04-12 14:37:57,937 basehttp 7344 12584 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 14:38:06,725 views 7344 12584 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:38:06,732 basehttp 7344 12584 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 14:38:17,809 basehttp 7344 12584 "GET /homework3 HTTP/1.1" 301 0
INFO 2024-04-12 14:38:17,813 views 7344 8556 Посещение страницы hw_app3.views: index
INFO 2024-04-12 14:38:17,814 basehttp 7344 8556 "GET /homework3/ HTTP/1.1" 200 433
ERROR 2024-04-12 14:38:43,359 log 7344 8556 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 14:38:43,361 basehttp 7344 8556 "GET /homework3/client/1/orders/ HTTP/1.1" 500 75006
INFO 2024-04-12 15:09:26,515 autoreload 11664 2892 Watching for file changes with StatReloader
WARNING 2024-04-12 15:09:28,819 log 11664 12532 Not Found: /
WARNING 2024-04-12 15:09:28,821 basehttp 11664 12532 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 15:09:37,605 views 11664 12532 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:09:37,625 basehttp 11664 12532 "GET /homework3/ HTTP/1.1" 200 433
ERROR 2024-04-12 15:10:13,563 log 11664 12532 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders.html
ERROR 2024-04-12 15:10:13,572 basehttp 11664 12532 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85314
ERROR 2024-04-12 15:10:15,557 log 11664 12532 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders.html
ERROR 2024-04-12 15:10:15,564 basehttp 11664 12532 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85040
INFO 2024-04-12 15:12:03,819 autoreload 11664 2892 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py changed, reloading.
INFO 2024-04-12 15:12:05,572 autoreload 14344 7176 Watching for file changes with StatReloader
ERROR 2024-04-12 15:12:06,503 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:12:06,509 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
ERROR 2024-04-12 15:12:09,490 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:12:09,505 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
ERROR 2024-04-12 15:15:33,935 log 14344 14316 Internal Server Error: /homework3/client/1/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:15:33,944 basehttp 14344 14316 "GET /homework3/client/1/orders/ HTTP/1.1" 500 85257
INFO 2024-04-12 15:16:52,201 autoreload 14344 7176 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 15:16:53,854 autoreload 15196 13944 Watching for file changes with StatReloader
ERROR 2024-04-12 15:16:56,857 log 15196 14016 Internal Server Error: /homework3/client/1/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 42, in client_orders_view
    return render(request, 'client_orders_view.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_orders_view.html
ERROR 2024-04-12 15:16:56,868 basehttp 15196 14016 "GET /homework3/client/1/ HTTP/1.1" 500 85036
INFO 2024-04-12 15:18:41,572 autoreload 15196 13944 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\urls.py changed, reloading.
INFO 2024-04-12 15:18:43,536 autoreload 7528 9616 Watching for file changes with StatReloader
WARNING 2024-04-12 15:18:43,976 log 7528 9384 Not Found: /homework3/client/1/
WARNING 2024-04-12 15:18:43,978 basehttp 7528 9384 "GET /homework3/client/1/ HTTP/1.1" 404 2926
WARNING 2024-04-12 15:18:56,773 log 7528 9384 Not Found: /homework3/client/1//orders/
WARNING 2024-04-12 15:18:56,775 basehttp 7528 9384 "GET /homework3/client/1//orders/ HTTP/1.1" 404 2950
INFO 2024-04-12 15:19:00,690 basehttp 7528 9384 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
ERROR 2024-04-12 15:19:25,477 log 7528 9384 Internal Server Error: /homework3/client/0/orders/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 21, in client_orders_view
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hw_app3.models.Client.DoesNotExist: Client matching query does not exist.
ERROR 2024-04-12 15:19:25,483 basehttp 7528 9384 "GET /homework3/client/0/orders/ HTTP/1.1" 500 75759
INFO 2024-04-12 15:19:33,017 basehttp 7528 9384 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:23,334 autoreload 7528 9616 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py changed, reloading.
INFO 2024-04-12 15:21:25,694 autoreload 10920 7176 Watching for file changes with StatReloader
INFO 2024-04-12 15:21:26,074 basehttp 10920 580 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:34,918 basehttp 10920 580 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:37,871 basehttp 10920 580 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:21:58,349 basehttp 10920 580 "GET /homework3/client/4/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:27:52,049 views 10920 11152 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:27:52,052 basehttp 10920 11152 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:33:11,603 autoreload 10920 7176 C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\models.py changed, reloading.
INFO 2024-04-12 15:33:13,045 autoreload 14828 5692 Watching for file changes with StatReloader
INFO 2024-04-12 15:34:26,273 autoreload 14476 14556 Watching for file changes with StatReloader
WARNING 2024-04-12 15:34:28,276 log 14476 12424 Not Found: /
WARNING 2024-04-12 15:34:28,279 basehttp 14476 12424 "GET / HTTP/1.1" 404 2393
INFO 2024-04-12 15:34:44,601 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:34:44,617 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:35:08,618 basehttp 14476 12424 "GET /homework3/client/1/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:14,906 basehttp 14476 12424 "GET /homework3/client/2/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:20,030 basehttp 14476 12424 "GET /homework3/client/5/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:35:41,745 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 319
INFO 2024-04-12 15:39:15,649 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 1034
INFO 2024-04-12 15:39:22,838 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:39:22,842 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 433
INFO 2024-04-12 15:41:18,711 views 14476 12424 Посещение страницы hw_app3.views: index
ERROR 2024-04-12 15:41:18,797 log 14476 12424 Internal Server Error: /homework3/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: hw_app3.base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app3\views.py", line 13, in index
    return render(request, 'hw_app3/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: hw_app3.base.html
ERROR 2024-04-12 15:41:18,808 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 500 125824
INFO 2024-04-12 15:41:47,759 views 14476 12424 Посещение страницы hw_app3.views: index
INFO 2024-04-12 15:41:47,766 basehttp 14476 12424 "GET /homework3/ HTTP/1.1" 200 326
INFO 2024-04-12 15:41:55,437 basehttp 14476 12424 "GET /homework3/client/4/orders/ HTTP/1.1" 200 1034
INFO 2024-04-12 15:42:26,236 basehttp 14476 12424 "GET /homework3/client/1/orders/ HTTP/1.1" 200 674
INFO 2024-04-13 22:10:01,657 autoreload 8820 11164 Watching for file changes with StatReloader
INFO 2024-04-13 22:17:20,518 autoreload 5544 3560 Watching for file changes with StatReloader
WARNING 2024-04-13 22:17:24,031 log 5544 12120 Not Found: /
WARNING 2024-04-13 22:17:24,031 basehttp 5544 12120 "GET / HTTP/1.1" 404 2503
WARNING 2024-04-13 22:17:24,206 log 5544 12120 Not Found: /favicon.ico
WARNING 2024-04-13 22:17:24,218 basehttp 5544 12120 "GET /favicon.ico HTTP/1.1" 404 2554
INFO 2024-04-13 22:17:41,782 views 5544 12120 Посещение страницы hw_app4.views: index
INFO 2024-04-13 22:17:41,794 basehttp 5544 12120 "GET /homework4/ HTTP/1.1" 200 326
INFO 2024-04-13 22:18:05,622 views 5544 12120 Посещение страницы hw_app4.views: about
INFO 2024-04-13 22:18:05,625 basehttp 5544 12120 "GET /homework4/about/ HTTP/1.1" 200 279
WARNING 2024-04-13 22:18:22,496 log 5544 12120 Not Found: /homework4/about/upload/
WARNING 2024-04-13 22:18:22,498 basehttp 5544 12120 "GET /homework4/about/upload/ HTTP/1.1" 404 3233
ERROR 2024-04-13 22:18:50,139 log 5544 12120 Internal Server Error: /homework4/upload/
Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\homework_1\hw_app4\views.py", line 60, in upload_image
    return render(request, 'hw_app4/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\JaneM\PycharmProjects\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-13 22:18:50,153 basehttp 5544 12120 "GET /homework4/upload/ HTTP/1.1" 500 127614
INFO 2024-04-13 22:20:42,860 basehttp 5544 12120 "GET /homework4/upload/ HTTP/1.1" 200 664
INFO 2024-04-13 22:22:54,650 basehttp 5544 12120 "POST /homework4/upload/ HTTP/1.1" 200 664
